# Generated by Django 6.1 on 2026-09-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0002_station_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='arrival',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='classes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='train',
            name='departure',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_number',
            field=models.IntegerField(),
        ),
    ]
