# Generated by Django 6.1 on 2026-09-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0003_train_arrival_train_classes_train_departure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainroute',
            name='day_number',
            field=models.IntegerField(default=1),
        ),
    ]
