# Generated by Django 6.1 on 2026-09-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0004_trainroute_day_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='journey_days',
            field=models.IntegerField(default=1),
        ),
    ]
