# Generated by Django 6.1 on 2026-09-08 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0007_classtype_remove_trainclass_class_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_destinations', to='railway.station'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='pnr',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='starting_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booking_starts', to='railway.station'),
        ),
    ]
