# Generated by Django 6.1 on 2026-09-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0008_booking_destination_station_booking_passengers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='classes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_trains', to='railway.station'),
        ),
        migrations.AlterField(
            model_name='train',
            name='journey_days',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_trains', to='railway.station'),
        ),
        migrations.AlterField(
            model_name='train',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
