# Generated by Django 6.1 on 2026-09-10 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0009_alter_train_classes_alter_train_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainroute',
            name='day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainroute',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='railway.station'),
        ),
        migrations.AlterField(
            model_name='trainroute',
            name='stop_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
