# Generated by Django 6.1 on 2026-09-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0010_alter_trainroute_day_number_alter_trainroute_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='route_map',
            field=models.ImageField(blank=True, null=True, upload_to='route_maps/'),
        ),
    ]
