# Generated by Django 6.1 on 2026-09-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0013_staffmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='railwayuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
