# Generated by Django 6.1 on 2026-09-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('railway', '0014_railwayuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmessage',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffmessage',
            name='staff_reply',
            field=models.TextField(blank=True, null=True),
        ),
    ]
